version: 0.2
phases:
  pre_build:
    commands:
      – apt-get update -y
      – apt-get install -y 
      – apt-get update -y
      – apt-get install -y openjdk-8-jdk
      – apt-get install -y maven
      – apt install docker.io
      - docker login -u kiranpayavuala -p kiranPAY1
  build:
    commands:
      – mvn clean
      – mvn install
      - echo Building the Docker image...
      - docker build -t kiranpayyavuala/myapp:1.11 .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push kiranpayyavuala/myapp:1.11
